
[window]
dimensions = { columns = 200, lines = 50 }
opacity = 0.98
decorations_theme_variant = "Dark"

[font]
normal = { family = "FiraCodeNerdFontMono", style = "Retina" }
offset = { x = 0, y = 1 }

[bell]
animation = "Ease"

[colors.primary]
background = "#31363b"

[general]
live_config_reload = true

[terminal]
shell = { program = "/usr/bin/zsh" }
