---
- name: Grant passwordless sudo to ansibleSetup user
  hosts: localhost
  become: yes # This playbook needs to be run as a user with sudo privileges
  tasks:
    - name: Ensure ansibleSetup user is present
      ansible.builtin.user:
        name: ansibleSetup
        state: present

    - name: Allow ansibleSetup user to run sudo without password
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^ansibleSetup"
        line: "ansibleSetup ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

- name: Arch Linux Development Environment Setup
  hosts: localhost
  become_user: ansibleSetup
  become: yes

  tasks:
    - name: Retry installing failed packages using yay
      yay:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - nitch
        - pipes-rs-git

  post_tasks:
    - name: Display finish message
      debug:
        msg: "Setup Done!"

- name: Revoke passwordless sudo from ansibleSetup user
  hosts: localhost
  become: yes # Back to running as a privileged user to remove the passwordless sudo
  tasks:
    - name: Remove ansibleSetup user from sudoers
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: absent
        regexp: "^ansibleSetup"
